name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy_to_digitalocean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: post call to deploy
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
          DO_APP_ID: ${{ secrets.DO_APP_ID }}
        run: |
          curl -X POST -H "Authorization: Bearer ${{ env.DO_ACCESS_TOKEN }}" "https://api.digitalocean.com/v2/apps/${{ env.DO_APP_ID }}/deployments"


